version: '3.8'
services:
  producer-metrics: 
    build:
      context: ./
      dockerfile: ./pDockerfile
    volumes:
      - ./confd:/app/confd
      - ./logs:/app/logs

  consumer-metrics: 
    build: 
      context: ./
      dockerfile: ./cDockerfile
    volumes:
      - ./confd:/app/confd
      - ./logs:/app/logs

