version: '3.8'
services:
  producer-metrics: 
    build:
      context: ./
      target: producer
    volumes:
      - ./confd:/app/confd
      - ./logs:/app/logs

  consumer-metrics: 
    build: 
      context: ./
      target: consumer
    volumes:
      - ./confd:/app/confd
      - ./logs:/app/logs

